/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dthrpvpuzinmevrvqlhv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0aHJwdnB1emlubWV2cnZxbGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTU3ODUsImV4cCI6MjA3MDg3MTc4NX0.Ts_PJLD0zEHjEg3iSFJfpqpIOm1FLAhEuzKud3ZFUjg"

// Quick setup helpers - run in browser console: 
// tuneTonAPI.setupDatabase().then(console.log)
// tuneTonAPI.fixRLS().then(console.log)  // Fix all 29 RLS security errors
const baseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-82f19583`
const headers = { 'Authorization': `Bearer ${publicAnonKey}`, 'Content-Type': 'application/json' }

export const tuneTonAPI = {
  async setupDatabase() {
    const res = await fetch(`${baseUrl}/setup-database`, { method: 'POST', headers })
    return await res.json()
  },
  async fixRLS() {
    const res = await fetch(`${baseUrl}/fix-rls`, { method: 'POST', headers })
    return await res.json()
  },
  async testConnection() {
    const res = await fetch(`${baseUrl}/test-db`, { headers })
    return await res.json()
  },
  async createUser(data: any) {
    const res = await fetch(`${baseUrl}/auth/user`, { method: 'POST', headers, body: JSON.stringify(data) })
    return await res.json()
  },
  async getComments(type: string, id: string) {
    const res = await fetch(`${baseUrl}/comments/${type}/${id}`, { headers })
    return await res.json()
  },
  async addComment(data: any) {
    const res = await fetch(`${baseUrl}/comments`, { method: 'POST', headers, body: JSON.stringify(data) })
    return await res.json()
  },
  async toggleLike(userId: string, type: string, id: string) {
    const res = await fetch(`${baseUrl}/like`, { method: 'POST', headers, body: JSON.stringify({ user_id: userId, entity_type: type, entity_id: id }) })
    return await res.json()
  }
}